{% set name = "i18n" %}
{% set version = "1.4.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: bb633854267df9de1c977c9a995764fdf674ab77f4dc87da48000d24523d113a

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-concurrent-ruby >=1.0,<2

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/MIT-LICENSE
  summary: New wave Internationalization support for Ruby.

  doc_url: http://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/ruby-i18n/{{ name }}

extra:
  recipe-maintainers:
    - sodre
